FORMAT: 1A
HOST: http://localhost:8080/

# im360

IM360 API

## HintsService v1.0 [/HintsService/v1.0/rest/]

### Cash report [GET /HintsService/v1.0/rest/report/cash/userId/{userId}/restaurantId/{restaurantId}/closeDate/{closeDate}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + closeDate: `2016-01-26` (number, required)


+ Response 200 (application/json)

        {"resultCode":"success","details":[{"register":"ff8081815277cc0a01527c5379ad05cf","time_open":"09:00 AM","time_closed":"02:58 PM","expected_cash":3589.46,"actual_cash":3592.0,"cash_difference":-2.54,"expected_debit":1515.0,"actual_debit":1515.0,"running_debit_sum":1515.0,"debit_difference":0.0,"expected_total":5104.46,"actual_total":5107.0,"total_difference":-2.54,"cashier":"TAYLOR","manager":"JAMINA KNOWLES"},{"register":"ff808081527bdf7c01527c4ec7ed018e","time_open":"09:00 AM","time_closed":"03:00 PM","expected_cash":4047.34,"actual_cash":3932.0,"cash_difference":115.34,"expected_debit":2075.0,"actual_debit":2075.0,"running_debit_sum":2075.0,"debit_difference":0.0,"expected_total":6122.34,"actual_total":6007.0,"total_difference":115.34,"cashier":"TAYLOR","manager":"JAMINA KNOWLES"}]}


### Cash report for non-existing restaurantId [GET /HintsService/v1.0/rest/report/cash/userId/{userId}/restaurantId/-1/closeDate/{closeDate}]
+ Parameters
    + userId: `1` (number, required)
    + closeDate: `2016-01-26` (number, required)


+ Response 200 (application/json)

        {"resultCode":"fail"}


### Profit report [GET /HintsService/v1.0/rest/report/profit/userId/{userId}/restaurantId/{restaurantId}/startDate/{startDate}/endDate/{endDate}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + startDate: `2016-01-01` (string, required)
    + endDate: `2016-01-01` (string, required)


+ Response 200 (application/json)

        {"resultCode":"success","details":[{"type":"FLOWER","strain":"91 OG KUSH","option":"SOIL - ORGANIC - LED","tier":"60","cost":209.52750000000003,"grams":22.75,"profit":378.0377999999999,"revenue":345.2399999999999,"profit_per_gram":7.407046153846148,"net_profit":135.71249999999986},{"type":"FLOWER","strain":"BLOCKHEAD","option":"SOIL - ORGANIC","tier":"45","cost":1206.2925000000005,"grams":168.25,"profit":2151.1384499999986,"revenue":1964.5099999999975,"profit_per_gram":5.615726300148577,"net_profit":758.217499999997}]}


### Profit report for non-existing restaurantId [GET /HintsService/v1.0/rest/report/profit/userId/{userId}/restaurantId/-1/startDate/{startDate}/endDate/{endDate}]
+ Parameters
    + userId: `1` (number, required)
    + startDate: `2016-01-01` (string, required)
    + endDate: `2016-01-01` (string, required)


+ Response 200 (application/json)

        {"resultCode":"fail"}


### Loss report [GET /HintsService/v1.0/rest/report/loss/userId/{userId}/restaurantId/{restaurantId}/startDate/{startDate}/endDate/{endDate}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + startDate: `2016-01-01` (string, required)
    + endDate: `2016-01-20` (string, required)


+ Response 200 (application/json)

        {"resultCode":"success","details":[{"type":"EXTRACT","strain":"ACDC","option":"OIL - ACTIVATED - 5:1","tier":"70","grams_per_jar":1.0,"jars_lost":1,"total_grams":1.0,"total_cost":35.0,"cost_per_gram":35.0},{"type":"EXTRACT","strain":"ACDC","option":"OIL - ACTIVATED - 10:1","tier":"70","grams_per_jar":1.0,"jars_lost":1,"total_grams":1.0,"total_cost":35.0,"cost_per_gram":35.0}]}


### Loss report for non-existing restaurantId [GET /HintsService/v1.0/rest/report/loss/userId/{userId}/restaurantId/-1/startDate/{startDate}/endDate/{endDate}]
+ Parameters
    + userId: `1` (number, required)
    + startDate: `2016-01-01` (string, required)
    + endDate: `2016-01-20` (string, required)


+ Response 200 (application/json)

        {"resultCode":"fail"}


### Product stock [GET /HintsService/v1.0/rest/product/stock/userId/{userId}/restaurantId/{restaurantId}/productId/{productId}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + productId: `004828e4-5c03-11e5-a043-4439c455558d` (string, required)


+ Response 200 (application/json)

                {"resultCode":"success","units":0.0}
                
### Payment report [GET /HintsService/v1.0/rest/report/payment/userId/{userId}/restaurantId/{restaurantId}/startDate/{startDate}/endDate/{endDate}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + startDate: `2016-01-01` (string, required)
    + endDate: `2016-01-01` (string, required)


+ Response 200 (application/json)

                {"resultCode":"success","details":[{"type":"CASH","cash":19957.468784999975,"tax":1731.4698945890377},{"type":"CASHLESS_ATM","cash":6525.0,"tax":566.0958904109584}]}


### Payment report for non-existing restaurantId [GET /HintsService/v1.0/rest/report/payment/userId/{userId}/restaurantId/-1/startDate/{startDate}/endDate/{endDate}]
+ Parameters
    + userId: `1` (number, required)
    + startDate: `2016-01-01` (string, required)
    + endDate: `2016-01-01` (string, required)


+ Response 200 (application/json)

                {"resultCode":"fail"}


### Ticket list [GET /HintsService/v1.0/rest/report/tickets/userId/{userId}/restaurantId/{restaurantId}/date/{date}/timeStart/{timeStart}/timeEnd/{timeEnd}/userIdList/{userIdList}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + date: `2015-04-24` (string, required)
    + timeStart: `00:11:00` (string, required)
    + timeEnd: `12:12:22` (string, required)
    + userIdList: `ff8081814968fc4201496905e785000b,ff8081814968fc4201496906c85d000d` (string, required)


+ Response 200 (application/json)

                {"resultCode":"success","details":[{"ID":"ff8081814cea39ee014cea444ba40001","visibleId":78296,"date":"2015-04-24","time":"00:11:53","total":120.00105,"NAME":"SHAREEF","user_id":"ff8081814968fc4201496905e785000b","payments":[{"type":"CASH","amount":120.00105},{"type":"CASHLESS_ATM","amount":0.0}]},{"ID":"ff8081814cea39ee014cea4511ff0009","visibleId":78298,"date":"2015-04-24","time":"00:12:22","total":-120.00105,"NAME":"SHAREEF","user_id":"ff8081814968fc4201496905e785000b","payments":[{"type":"CASH","amount":-120.00105},{"type":"CASHLESS_ATM","amount":0.0}]}]}


### Units report [GET /HintsService/v1.0/rest/report/units/userId/{userId}/restaurantId/{restaurantId}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)


+ Response 200 (application/json)

                {"resultCode":"success","details":[{"type":"FLOWER","strain":"91 OG KUSH","option":"SOIL - ORGANIC","tier":"60","units":3.0,"total_cost":12000.0,"cost_per_unit":4000.0},{"type":"FLOWER","strain":"91 OG KUSH","option":"SOIL - ORGANIC - LED","tier":"60","units":1.0,"total_cost":4000.0,"cost_per_unit":4000.0},{"type":"FLOWER","strain":"ANIMAL COOKIES","option":"ROCKWOOL - HYDROPONIC","tier":"45","units":2.0,"total_cost":6500.0,"cost_per_unit":3250.0}]}


### Units report for non-existing restaurantId [GET /HintsService/v1.0/rest/report/units/userId/{userId}/restaurantId/-1]
+ Parameters
    + userId: `1` (number, required)


+ Response 200 (application/json)

                {"resultCode":"fail"}


### Sales report [GET /HintsService/v1.0/rest/report/sales/userId/{userId}/restaurantId/{restaurantId}/startDate/{startDate}/endDate/{endDate}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + startDate: `2016-01-01` (string, required)
    + endDate: `2016-01-01` (string, required)


+ Response 200 (application/json)

                {"resultCode":"success","details":[{"type":"FLOWER","strain":"91 OG KUSH","option":"SOIL - ORGANIC - LED","tier":"60","gross":378.0377999999999,"net":345.2399999999999,"tax":32.7978,"discount":12.001199999999997,"usage_tax":0.0},{"type":"FLOWER","strain":"BLOCKHEAD","option":"SOIL - ORGANIC","tier":"45","gross":2151.1384499999986,"net":1964.5099999999975,"tax":186.62844999999973,"discount":13.490400000000001,"usage_tax":0.0}]}


#@# Ticket details [GET /HintsService/v1.0/rest/details/ticket/userId/{userId}/restaurantId/{restaurantId}/ticketVisibleId/{ticketVisibleId}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + ticketVisibleId: `70385` (number, required)


+ Response 200 (application/json)

                {"resultCode":"success","products":[{"id":"crumb35","amount":1.0,"price":27.4,"description":"CRUMB 3.5g","option":null,"type":"SHAKE/CRUMB","comment":null}]}


### Bag list with ATTR1!=null for non-existing restaurantId [GET /HintsService/v1.0/rest/report/bags/userId/{userId}/restaurantId/-1/status/{status}/attr1/{attr1}]
+ Parameters
    + userId: `1` (number, required)
    + status: `0` (number, required)
    + attr1: `LAB` (string, required)


+ Response 200 (application/json)

                {"resultCode":"fail"}


### Bag list with ATTR1!=null [GET /HintsService/v1.0/rest/report/bags/userId/{userId}/restaurantId/{restaurantId}/status/{status}/attr1/{attr1}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + status: `0` (number, required)
    + attr1: `LAB` (string, required)


+ Response 200 (application/json)

                {"resultCode":"success","bags":[{"id":"39245bc8-b33d-11e5-8802-b8aeed795ea3","visibleId":"707OGKUSHS16010415451-04","price_per_unit":4000.0,"tier_name":"60","category_id":"3917f994-b33d-11e5-8802-b8aeed795ea3","parent_category_id":"39168b9a-b33d-11e5-8802-b8aeed795ea3","category_name":"707 OG KUSH"},{"id":"9dcd03e5-adab-11e5-8802-b8aeed795ea3","visibleId":"91OGKUSHS15122813401-05","price_per_unit":4000.0,"tier_name":"60","category_id":"9dc07ae4-adab-11e5-8802-b8aeed795ea3","parent_category_id":"9dbf60c9-adab-11e5-8802-b8aeed795ea3","category_name":"91 OG KUSH"}]}


### Bag list with ATTR1=null [GET /HintsService/v1.0/rest/report/bags/userId/{userId}/restaurantId/{restaurantId}/status/{status}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + status: `0` (number, required)


+ Response 200 (application/json)

                {"resultCode":"success","bags":[{"id":"9dccbe5c-adab-11e5-8802-b8aeed795ea3","visibleId":"91OGKUSHS15122813401-04","price_per_unit":4000.0,"tier_name":"60","category_id":"9dc07ae4-adab-11e5-8802-b8aeed795ea3","parent_category_id":"9dbf60c9-adab-11e5-8802-b8aeed795ea3","category_name":"91 OG KUSH"},{"id":"348ed58d-b33d-11e5-8802-b8aeed795ea3","visibleId":"91OGKUSHS16010415451-01","price_per_unit":4000.0,"tier_name":"60","category_id":"34811816-b33d-11e5-8802-b8aeed795ea3","parent_category_id":"3438974d-b33d-11e5-8802-b8aeed795ea3","category_name":"91 OG KUSH"}]}


### List of users [GET /HintsService/v1.0/rest/user/list/userId/{userId}/restaurantId/{restaurantId}/groupId/{groupId}/active/{active}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + groupId: `2` (number, required)
    + active: `1` (number, required)


+ Response 200 (application/json)

                {"resultCode":"success","users":[{"id":13,"first_name":"Andrew","last_name":"Do"},{"id":37,"first_name":"Barry","last_name":"Lai"},{"id":15,"first_name":"Christopher","last_name":"Buerger"},{"id":21,"first_name":"Esther","last_name":"Darretta"},{"id":24,"first_name":"Firas","last_name":"Ayyad"},{"id":20,"first_name":"Jamina","last_name":"Knowles"},{"id":17,"first_name":"Mike","last_name":"Do"},{"id":10,"first_name":"Shareef","last_name":"ElSissi"},{"id":11,"first_name":"Soufyan","last_name":"AbouAhmed"},{"id":23,"first_name":"Taylor","last_name":"Melendy"},{"id":12,"first_name":"ThuLinh","last_name":"Delestrez"}]}


### Product stock report [GET /HintsService/v1.0/rest/report/stock/userId/{userId}/restaurantId/{restaurantId}/date/{date}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + date: `2016-01-26` (string, required)


+ Response 200 (application/json)

                {"resultCode":"success","details":[{"type":"FLOWER","strain":"91 OG KUSH","option":"SOIL - ORGANIC - LED","tier":"60","grams_per_jar":7.0,"unite":5.0,"total_grams":35.0,"total_cost":308.1324969736987,"cost_per_gram":8.803785627819963},{"type":"FLOWER","strain":"91 OG KUSH","option":"SOIL - ORGANIC - LED","tier":"60","grams_per_jar":3.5,"unite":35.0,"total_grams":122.5,"total_cost":1078.4637394079455,"cost_per_gram":8.803785627819963}]}


### List of strains [GET /HintsService/v1.0/rest/strain/list/userId/{userId}/restaurantId/{restaurantId}/active/{active}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + active: `1` (number, required)


+ Response 200 (application/json)

                {"resultCode":"success","strains":[{"id":"3864eb40-b33d-11e5-8802-b8aeed795ea3","name":"707 OG KUSH"},{"id":"69f0b5d6-3bb8-11e5-a043-4439c455558d","name":"9 POUND HAMMER"},{"id":"34822479-b33d-11e5-8802-b8aeed795ea3","name":"91 OG KUSH"}]}


### List of attributes [GET /HintsService/v1.0/rest/attribute/list/userId/{userId}/restaurantId/{restaurantId}/active/{active}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + active: `1` (number, required)


+ Response 200 (application/json)

                {"resultCode":"success","attributes":[{"id":8,"name":"CBD"},{"id":1,"name":"HYBRID"},{"id":5,"name":"I/S"},{"id":2,"name":"INDICA"},{"id":3,"name":"KUSH"},{"id":9,"name":"NONE"},{"id":6,"name":"S/I"},{"id":4,"name":"SATIVA"}]}


### List of options [GET /HintsService/v1.0/rest/option/list/userId/{userId}/restaurantId/{restaurantId}/active/{active}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + active: `1` (number, required)


+ Response 200 (application/json)

                {"resultCode":"success","options":[{"id":46,"name":"100 PUFFS"},{"id":28,"name":"CLEAN GREEN"}]}


### Tiers costs [GET /HintsService/v1.0/rest/tier/costs/userId/{userId}/restaurantId/{restaurantId}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)


+ Response 200 (application/json)

                {"resultCode":"success","tiers":[{"id":1,"vendor":null,"tier":60,"cost":4000.0},{"id":2,"vendor":null,"tier":50,"cost":3500.0},{"id":3,"vendor":null,"tier":45,"cost":3250.0},{"id":4,"vendor":null,"tier":40,"cost":3000.0},{"id":5,"vendor":null,"tier":35,"cost":2750.0},{"id":6,"vendor":null,"tier":30,"cost":2500.0},{"id":7,"vendor":null,"tier":25,"cost":2000.0}]}


### Extracts list with ATTR1!=null for non-existing restaurantId  [GET /HintsService/v1.0/rest/report/extracts/userId/{userId}/restaurantId/-1/status/{status}/attr1/{attr1}]
+ Parameters
    + userId: `1` (number, required)
    + status: `0` (number, required)
    + attr1: `LAB` (string, required)


+ Response 200 (application/json)

                {"resultCode":"fail"}


### Extracts list with ATTR1!=null [GET /HintsService/v1.0/rest/report/extracts/userId/{userId}/restaurantId/{restaurantId}/status/{status}/attr1/{attr1}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + status: `0` (number, required)
    + attr1: `LAB` (string, required)


+ Response 200 (application/json)

                {"resultCode":"success","extractBags":[{"id":"9e608e83-81c2-11e5-b505-4439c455558d","visibleId":"100CV2101CV2151029153012","price_per_gram":null,"tier":30,"grams":null,"category_id":"9e3e9a24-81c2-11e5-b505-4439c455558d","parent_category_id":"bcd6a222-2a46-11e5-8243-4439c455558d","category_name":"THC BLEND"},{"id":"aec5ff51-a4f8-11e5-9ce5-b8aeed795ea3","visibleId":"ACDC151203172245","price_per_gram":null,"tier":70,"grams":null,"category_id":"68f32900-a50e-11e5-9ce5-b8aeed795ea3","parent_category_id":"68acafca-a50e-11e5-9ce5-b8aeed795ea3","category_name":"ACDC"},{"id":"8bd777d9-979a-11e5-8aba-4439c455558d","visibleId":"ACDCO15113011423-L","price_per_gram":null,"tier":70,"grams":null,"category_id":"8ba2309a-979a-11e5-8aba-4439c455558d","parent_category_id":"8b9df330-979a-11e5-8aba-4439c455558d","category_name":"ACDC"}]}


### Extracts list with ATTR1=null [GET /HintsService/v1.0/rest/report/extracts/userId/{userId}/restaurantId/{restaurantId}/status/{status}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + status: `0` (number, required)


+ Response 200 (application/json)

                {"resultCode":"success","extractBags":[{"id":"d66e0bdb-b437-11e5-8802-b8aeed795ea3","visibleId":"BLUEDREAMO16010521397","price_per_gram":25.0,"tier":50,"grams":124.0,"category_id":"76d8ea04-9ad3-11e5-9140-4439c455558d","parent_category_id":"76b86d5a-9ad3-11e5-9140-4439c455558d","category_name":"BLUE DREAM"},{"id":"ef0eccac-c13a-11e5-8802-b8aeed795ea3","visibleId":"CRIPPLERO16012211048","price_per_gram":22.5,"tier":45,"grams":117.0,"category_id":"2b1aa093-bfc5-11e5-8802-b8aeed795ea3","parent_category_id":"2b15bd7e-bfc5-11e5-8802-b8aeed795ea3","category_name":"CRIPPLER"}]}


### Extracts costs [GET /HintsService/v1.0/rest/extract/costs/userId/{userId}/restaurantId/{restaurantId}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)


+ Response 200 (application/json)

                {"resultCode":"success","tiers":[{"id":1,"vendor":null,"tier":60,"cost":4000.0},{"id":2,"vendor":null,"tier":50,"cost":3500.0},{"id":3,"vendor":null,"tier":45,"cost":3250.0},{"id":4,"vendor":null,"tier":40,"cost":3000.0},{"id":5,"vendor":null,"tier":35,"cost":2750.0},{"id":6,"vendor":null,"tier":30,"cost":2500.0},{"id":7,"vendor":null,"tier":25,"cost":2000.0}]}


### Get current inventory for non-existing restaurantId [GET /HintsService/v1.0/rest/report/inventory/userId/{userId}/restaurantId/-1]
+ Parameters
    + userId: `1` (number, required)


+ Response 200 (application/json)

                {"resultCode":"fail"}


### Get current inventory [GET /HintsService/v1.0/rest/report/inventory/userId/{userId}/restaurantId/{restaurantId}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)


+ Response 200 (application/json)

                {"resultCode":"success","inventory":[{"id":"087b908f-241b-11e5-8243-4439c455558d","strain_name":"HARLE-TSU","options":"WAX - NUG RUN 10:1","tier_name":"60","total_grams":28.0,"total_cost":840.0,"cost_per_gram":30.0,"type":"extract","details":[{"grams_per_jar":1.0,"quantity":28}]}]}


### Get inventory list for non-existing restaurantId [GET /HintsService/v1.0/rest/report/inventory/list/userId/{userId}/restaurantId/-1/attr1/{attr1}]
+ Parameters
    + userId: `1` (number, required)
    + attr1: `ACTIVE` (string, required)


+ Response 200 (application/json)

                {"resultCode":"fail"}


### Get inventory list [GET /HintsService/v1.0/rest/report/inventory/list/userId/{userId}/restaurantId/{restaurantId}/attr1/{attr1}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + attr1: `ACTIVE` (string, required)


+ Response 200 (application/json)

                {"resultCode":"success","inventories":[{"id":"8722d41b-bd3b-11e5-8802-b8aeed795ea3","visible_id":2128,"strain_name":"91 OG KUSH","option":"SOIL - ORGANIC - LED","tier_name":"60","date":"2016-01-17","cost":4000.0,"starting_weight":456.0,"ending_weight":452.75,"total_loss":3.25,"grams_sold":249.25,"grams_inventory":203.5,"status":"ACTIVE"}]}


### Get print information for non-existing restaurantId [GET /HintsService/v1.0/rest/print/information/userId/{userId}/restaurantId/-1/categoryId/{categoryId}/tier/{tier}]
+ Parameters
    + userId: `1` (number, required)
    + categoryId: `0012f93a-61da-11e4-9fc3-4439c455558d` (string, required)
    + tier: `25` (number, required)


+ Response 200 (application/json)

                {"resultCode":"fail"}


### Get print information [GET /HintsService/v1.0/rest/print/information/userId/{userId}/restaurantId/{restaurantId}/categoryId/{categoryId}/tier/{tier}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + categoryId: `0012f93a-61da-11e4-9fc3-4439c455558d` (string, required)
    + tier: `25` (number, required)


+ Response 200 (application/json)

                {"resultCode":"success","details":[{"product":"039a85a8-61da-11e4-9fc3-4439c455558d","tier":"45","price":82.19,"code":"0150","attribute":"KUSH","name":"BANANA KUSH","options":"","grams":"7 GRAMS","weight":7.0},{"product":"03a4c2cb-61da-11e4-9fc3-4439c455558d","tier":"45","price":41.1,"code":"0151","attribute":"KUSH","name":"BANANA KUSH","options":"","grams":"3.5 GRAMS","weight":3.5},{"product":"03b1d592-61da-11e4-9fc3-4439c455558d","tier":"45","price":20.55,"code":"0152","attribute":"KUSH","name":"BANANA KUSH","options":"","grams":"1.75 GRAMS","weight":1.75},{"product":"03c5ada5-61da-11e4-9fc3-4439c455558d","tier":"45","price":11.87,"code":"0153","attribute":"KUSH","name":"BANANA KUSH","options":"","grams":"1 GRAM","weight":1.0}]}


### Get flowers menu [GET /HintsService/v1.0/rest/menu/flowers/userId/{userId}/restaurantId/{restaurantId}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)


+ Response 200 (application/json)

                {"resultCode":"success","items":[{"category_name":"91 OG KUSH","attribute":"S/I","tier_name":"60","opttion":"SOIL - ORGANIC - LED","description":"THC 14.6% Cannabinoids 17.1% Terpenoids 1.9%","details":[{"size":1,"units":11,"price":"$20","sup":""},{"size":7,"units":3,"price":"$120","sup":""},{"size":35,"units":33,"price":"$60","sup":""},{"size":175,"units":32,"price":"$30","sup":""}]}]}


### Get flowers menu for non-existing restaurantId [GET /HintsService/v1.0/rest/menu/flowers/userId/{userId}/restaurantId/-1]
+ Parameters
    + userId: `1` (number, required)


+ Response 200 (application/json)

                {"resultCode":"fail"}


### Get extracts menu [GET /HintsService/v1.0/rest/menu/extracts/userId/{userId}/restaurantId/{restaurantId}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)


+ Response 200 (application/json)

                {"resultCode":"success","items":[{"id":"e35140c1-bfc3-11e5-8802-b8aeed795ea3","extract_cost_id":21,"category_name":"INVISIDAB INHALER","attribute":"NONE","option":"100 PUFFS","description":"THC -.-% Cannabinoids -.-% Terpenoids -.-%","price":"$100","sup":""}]}


### Get extracts menu for non-existing restaurantId [GET /HintsService/v1.0/rest/menu/extracts/userId/{userId}/restaurantId/-1]
+ Parameters
    + userId: `1` (number, required)

+ Response 200 (application/json)

                {"resultCode":"fail"}


### Get flowers shipments for non-existing restaurantId [GET /HintsService/v1.0/rest/shipments/flowers/userId/{userId}/restaurantId/-1/dateStart/{dateStart}/dateEnd/{dateEnd}]
+ Parameters
    + userId: `1` (number, required)
    + dateStart: `2016-01-01` (string, required)
    + dateEnd: `2016-01-26` (string, required)

+ Response 200 (application/json)

                {"resultCode":"fail"}


### Get flowers shipments [GET /HintsService/v1.0/rest/shipments/flowers/userId/{userId}/restaurantId/{restaurantId}/dateStart/{dateStart}/dateEnd/{dateEnd}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + dateStart: `2016-01-01` (string, required)
    + dateEnd: `2016-01-26` (string, required)

+ Response 200 (application/json)

                {"resultCode":"success","shipments":[{"id":"33a1ccaf-b33d-11e5-8802-b8aeed795ea3","visible_id":115,"vendor":"BROKER","date":"2016-01-04","price":169000.0,"units":48.0,"price_per_unit":3520.8333333333335}]}


### Get flowers shipment details for non-existing restaurantId [GET /HintsService/v1.0/rest/shipment/details/flowers/userId/{userId}/restaurantId/-1/shipmentId/{shipmentId}]
+ Parameters
    + userId: `1` (number, required)
    + shipmentId: `033adf93-9bb4-11e5-9140-4439c455558d` (string, required)

+ Response 200 (application/json)

                {"resultCode":"fail"}


### Get flowers shipment details [GET /HintsService/v1.0/rest/shipment/details/flowers/userId/{userId}/restaurantId/{restaurantId}/shipmentId/{shipmentId}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + shipmentId: `033adf93-9bb4-11e5-9140-4439c455558d` (string, required)

+ Response 200 (application/json)

                {"resultCode":"success","details":[{"id":"03c2947f-9bb4-11e5-9140-4439c455558d","category_name":"SILVER HAZE","option":"SOIL","tier":"40","units":2.0,"price_per_unit":3000.0,"price":6000.0,"sample_id":null,"visible_id":"SILVERHAZES15120516554-03"}]}


### Get extracts shipments for non-existing restaurantId [GET /HintsService/v1.0/rest/shipments/extracts/userId/{userId}/restaurantId/-1/dateStart/{dateStart}/dateEnd/{dateEnd}]
+ Parameters
    + userId: `1` (number, required)
    + dateStart: `2016-01-01` (string, required)
    + dateEnd: `2016-01-26` (string, required)

+ Response 200 (application/json)

                {"resultCode":"fail"}


### Get extracts shipments [GET /HintsService/v1.0/rest/shipments/extracts/userId/{userId}/restaurantId/{restaurantId}/dateStart/{dateStart}/dateEnd/{dateEnd}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + dateStart: `2016-01-01` (string, required)
    + dateEnd: `2016-01-26` (string, required)

+ Response 200 (application/json)

                {"resultCode":"success","shipments":[{"id":"e44930ef-b31f-11e5-8802-b8aeed795ea3","visible_id":114,"vendor":"WATERS","date":"2016-01-04","price":5670.0,"grams":252.0,"price_per_gram":22.5}]}


### Get extracts shipment details for non-existing restaurantId [GET /HintsService/v1.0/rest/shipment/details/extracts/userId/{userId}/restaurantId/-1/shipmentId/{shipmentId}]
+ Parameters
    + userId: `1` (number, required)
    + shipmentId: `033adf93-9bb4-11e5-9140-4439c455558d` (string, required)

+ Response 200 (application/json)

                {"resultCode":"fail"}


### Get extracts shipment details [GET /HintsService/v1.0/rest/shipment/details/extracts/userId/{userId}/restaurantId/{restaurantId}/shipmentId/{shipmentId}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `1` (number, required)
    + shipmentId: `fcb84e34-689b-11e5-ac36-4439c455558d` (string, required)

+ Response 200 (application/json)

                {"resultCode":"success","details":[{"id":"00957c7e-689c-11e5-ac36-4439c455558d","category_name":"LARRY OG","option":"OIL","tier":45,"grams":59.0,"price_per_gram":22.5,"price":1327.5,"sample_id":"1509ex029","visible_id":"LARRYOGO15100117248-L"}]}


### Update strain [POST /HintsService/v1.0/rest/strain/update/userId/{userId}/restaurantId/{restaurantId}/status/{status}/prevStrain/{prevStrain}/strain/{strain}/attribute/{attribute}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `-1` (number, required)
    + status: `1` (string, required)
    + prevStrain: `WHITE CASHMERE` (string, required)
    + strain: `WHITE CASHMERE 1` (string, required)
    + attribute: `HYBRID` (string, required)

+ Response 200 (application/json)

                {"resultCode":"fail"}


### Update strain attribute [POST /HintsService/v1.0/rest/strain/attribute/update/userId/{userId}/restaurantId/{restaurantId}/status/{status}/prevStrain/{prevStrain}/attribute/{attribute}]
+ Parameters
    + userId: `1` (number, required)
    + restaurantId: `-1` (number, required)
    + status: `1` (string, required)
    + prevStrain: `HYBRID` (string, required)
    + attribute: `HYBRID1` (string, required)

+ Response 200 (application/json)

                {"resultCode":"fail"}